# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
safe: true


# edit here to achieve your personal greatness
url: http://VishargShah.github.io/
title: Visharg Shah
author: Visharg Shah
description: Personal blog and resume
avatar: profile.png
email: vishargshah@gmail.com
github: VishargShah #username
twitter: Visharg
linkedin: vishargshah
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
